name: Winlator Rootfs Base Build Contaienr ARM64

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:

jobs:
  archlinux:
    runs-on: ubuntu-24.04-arm
    steps:
    #   - name: Clone repo
    #     uses: actions/checkout@v5
    #     with:
    #       sparse-checkout: |
    #         arch-bootstrap.sh
    #         Wlt-bcc.sh
    #         mount.sh


      - name: Setting chroot
        run: |
          cd /tmp
          git clone https://github.com/blazingcody0707/BCC.git BCC
          aria2c -s16 -x16 https://github.com/blazingcody0707/BCC/releases/download/archlinux-latest/archlinux-latest.tar.xz
          sudo tar xf archlinux-latest.tar.xz
          sudo cp /tmp/BCC/Wlt-bcc.sh /tmp/archlinux/tmp
          cp /tmp/BCC/mount.sh /tmp
          bash mount.sh mount archlinux
          sudo chroot archlinux bash -x /tmp/Wlt-bcc.sh || exit 1
          cd /tmp
          bash mount.sh unmount archlinux

      - name: Package
        run: |
          cd /tmp
          sudo tar -I 'xz -T$(nproc)' -cvf wlt-bcc.tar.xz archlinux

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Winlator BCC
          draft: false
          prerelease: false
          tag_name: wlt-bcc-latest
          body: |
            winlator rootfs BCC
          files: /tmp/wlt-bcc.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
